version: '3.7'

services:
  vespa:
    image: vespaengine/vespa
    container_name: vespa
    environment:
      VESPA_PORT: 8080
      VESPA_ADMIN_PORT: 19071
    expose:
      - "8080"     # Vespa HTTP API (Exposed internally)
      - "19071"    # Vespa Admin API (Exposed internally)
    volumes:
      - vespa_data:/opt/vespa/var
      - vespa_logs:/opt/vespa/logs
      - vespa_conf:/opt/vespa/conf
    restart: always

volumes:
  vespa_data:
  vespa_logs:
  vespa_conf:
